name: Build
on:
  workflow_dispatch:
  release:
    types: ["published"]
permissions:
  contents: read
jobs:
  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Install Flutter
        uses: subosito/flutter-action@v2.16.0
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          dart run build_runner build
          flutter gen-l10n
          flutter build windows
      - name: Add DLLs
        run: |
          cp C:\Windows\System32\msvcp140.dll build\windows\runner\Release\
          cp C:\Windows\System32\vcruntime140.dll build\windows\runner\Release\
          cp C:\Windows\System32\vcruntime140_1.dll build\windows\runner\Release\
      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/windows/runner/Release
